# -*- coding: utf-8 -*-
"""Validate release metadata before building artifacts."""

from __future__ import annotations

import os
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parents[1]


def main() -> int:
    version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
    errors: list[str] = []
    if not re.fullmatch(r"\d+\.\d+\.\d+", version):
        errors.append(f"VERSION must be semver-like, got {version!r}.")

    release_notes = ROOT / f"RELEASE_NOTES_{version}.md"
    if not release_notes.exists():
        errors.append(f"Missing release notes: {release_notes.name}.")

    expected_tag = f"v{version}"
    ref_type = os.environ.get("GITHUB_REF_TYPE")
    ref_name = os.environ.get("GITHUB_REF_NAME")
    if ref_type == "tag" and ref_name != expected_tag:
        errors.append(f"Git tag {ref_name!r} does not match VERSION {expected_tag!r}.")

    expected_strings = {
        "core/i18n.py": [
            f"VinaLab v{version}",
            f"Versão {version}",
            f"Version {version}",
            f"Generated by VinaLab v{version}",
        ],
        "packaging/windows/install_windows.ps1": [f'$Version = "{version}"'],
        "packaging/windows/VinaLab.iss": [f'#define MyAppVersion "{version}"'],
        ".github/workflows/release.yml": [f"RELEASE_NOTES_{version}.md"],
    }
    for relative_path, needles in expected_strings.items():
        text = (ROOT / relative_path).read_text(encoding="utf-8")
        for needle in needles:
            if needle not in text:
                errors.append(f"{relative_path} does not contain {needle!r}.")

    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    print(f"Release metadata is consistent for {version}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
